-- 한 줄 주석

/* 범위주석 */

-- SQL한 줄 실행 : ctrl + Enter

/* SYS관리자 계정으로 수행하는 SQL */
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER KH_LSH IDENTIFIED BY KH1234;

GRANT RESOURCE, CONNECT TO KH_LSH;

ALTER USER KH_LSH DEFAULT TABLESPACE
USERS QUOTA 20M ON USERS;